# Copyright (c) 2020-2029 GUARD Project (https://www.guard-project.eu)
# author: Alex Carrega <alessandro.carrega@cnit.it>

port: 9999
debug: false
project: GUARD
title: RESTable Test
description: Testing RESTable features.
commands:
  list:
    script: ls
    daemon: false
  current-dir:
    script: pwd
    daemon: false
configurations:
  test-json:
    path: tests/test.json
    format: json
  test-yaml:
    path: tests/test.yaml
    format: yaml
parameters:
  enabled:
    source: tests/test.json
    format: json
    xpath:
      - agent
      - enabled
