# Copyright (c) 2020-2029 Alex Carrega <contact@alexcarrega.com>
# author: Alex Carrega <contact@alexcarrega.com>

port: 9999
debug: True
name: Packetbeat
description: Service action controller.
commands:
  service-start:
    script: service packetbeat start
    daemon: false
  service-stop:
    script: service packetbeat stop
    daemon: false
  service-restart:
    script: service packetbeat restart
    daemon: false
  service-status:
    script: service packetbeat status
    daemon: false
